#This is the first comment line; it should be removed
# and this second line with a space after the hash should be removed

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> # <- uri with hash should be left alone, but this comment removed
PREFIX foi: <http://publishmydata.com/def/ontology/foi/>

SELECT * WHERE {
  # This should also be removed
  GRAPH ?g { #and this #dsf/># also
    ?s ?p ?o .
  }
}
LIMIT 7