## -- Some Header and Doc String like in yessparql

SELECT * WHERE {
  {
      SELECT * WHERE {
          GRAPH ?g {
            ?s ?p ?o .
          }
      }
      LIMIT ?myLimitVar
  }
  UNION
  {
      SELECT * WHERE {
          GRAPH ?g {
            ?s ?p ?o .
          }
      }
      limit 7
  }
}
LIMIT 1 OFFSET 0
